#define E_COULD_NOT_OPEN_MTDBLOCK 101
#define E_COULD_NOT_GET_MTDINFO 102
#define E_ERASING_MTDBLOCK_FAILED 103

#define E_TRANSFERING_MTDBLOCK 201

#define E_ERASING_MTDBLOCK 301
#define E_ERASED_MTDBLOCK 302

#define E_READY_TO_WRITE_MTDBLOCK 401
#define E_WRITTEN_MTDBLOCK 402
